name: Update and Release

on:
  workflow_dispatch:
    inputs:
      build-only:
        type: boolean
        default: true
  schedule:
    - cron: '0 5 * * 1,3,5'

env:
  PACKAGE: apache-httpd
  BUILD_ONLY: ${{ github.event_name == 'workflow_dispatch' && inputs.build-only }}

permissions:
  contents: write
  
jobs:
  build-and-release:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: .\apache-httpd
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_KEY_COMMIT_PUSH }}

    - name: Install Choco Auto Updates
      run: choco install au -y

    - name: Build Package
      id: build-package
      run: |
        .\update.ps1
        echo "VERSION=$Env:CHOCO_PACKAGE_VERSION" >> $Env:GITHUB_ENV

    - name: Commit and Push
      if: ${{ env.BUILD_ONLY != 'true' }}
      run: |
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git config user.name github-actions[bot]
        git fetch --force
        git add -A && git commit -m "Updated $Env:PACKAGE to $Env:VERSION" && git push
        
    # using a GitHub App will allow other workflows to trigger (on release)
    - name: Get UW Health Repo Bot Token
      if: ${{ env.BUILD_ONLY != 'true' }}
      id: uw-health-repo-bot
      uses: peter-murray/workflow-application-token-action@v2
      with:
        application_id: ${{ secrets.UW_HEALTH_REPO_BOT_APP_ID }}
        application_private_key: ${{ secrets.UW_HEALTH_REPO_BOT_PRIVATE_KEY }}

    - name: Release and Upload
      if: ${{ env.BUILD_ONLY != 'true' }}
      run: gh release create "v$Env:VERSION" --latest --title "Updated $Env:PACKAGE to $Env:VERSION" `
        --notes "<https://www.apachelounge.com/Changelog-2.4.html>" "$env:PACKAGE.$Env:VERSION.nupkg"
      env:
        GITHUB_TOKEN: ${{ steps.uw-health-repo-bot.outputs.token }}
